apiVersion: v1
kind: Secret
metadata:
  name: eci-secrets
  namespace: eci
type: Opaque
stringData:
  PAYMENT_SECRET_KEY: "eci-payment-signing-key-s2-2025"
  TOTALS_SIGNATURE_KEY: "eci-totals-hmac-key-s2-2025"
